export const GET_LIST_NOTARY_STAFF_START = 'GET_LIST_NOTARY_STAFF_START';
export const GET_LIST_NOTARY_STAFF_FAILED = 'GET_LIST_NOTARY_STAFF_FAILED';
export const GET_LIST_NOTARY_STAFF_SUCCESS = 'GET_LIST_NOTARY_STAFF_SUCCESS';
export const GET_LIST_NOTARY_STAFF = 'GET_LIST_NOTARY_STAFF';

export const LOAD_MORE_LIST_NOTARY_STAFF_START = 'LOAD_MORE_LIST_NOTARY_STAFF_START';
export const LOAD_MORE_LIST_NOTARY_STAFF_FAILED = 'LOAD_MORE_LIST_NOTARY_STAFF_FAILED';
export const LOAD_MORE_LIST_NOTARY_STAFF_SUCCESS = 'LOAD_MORE_LIST_NOTARY_STAFF_SUCCESS';
export const LOAD_MORE_LIST_NOTARY_STAFF = 'LOAD_MORE_LIST_NOTARY_STAFF';

export const REFRESH_LIST_NOTARY_STAFF_START = 'REFRESH_LIST_NOTARY_STAFF_START';
export const REFRESH_LIST_NOTARY_STAFF_FAILED = 'REFRESH_LIST_NOTARY_STAFF_FAILED';
export const REFRESH_LIST_NOTARY_STAFF_SUCCESS = 'REFRESH_LIST_NOTARY_STAFF_SUCCESS';
export const REFRESH_LIST_NOTARY_STAFF = 'REFRESH_LIST_NOTARY_STAFF';

export const GET_LIST_ADDRESS_NOTARY_CITY_START= 'GET_LIST_ADDRESS_NOTARY_CITY_START';
export const GET_LIST_ADDRESS_NOTARY_CITY_FAILED = 'GET_LIST_ADDRESS_NOTARY_CITY_FAILED';
export const GET_LIST_ADDRESS_NOTARY_CITY_SUCCESS = 'GET_LIST_ADDRESS_NOTARY_CITY_SUCCESS';
export const GET_LIST_ADDRESS_NOTARY_CITY = 'GET_LIST_ADDRESS_NOTARY_CITY';


export const GET_LIST_DISTRICT_NOTARY_START= 'GET_LIST_DISTRICT_NOTARY_START';
export const GET_LIST_DISTRICT_NOTARY_FAILED = 'GET_LIST_DISTRICT_NOTARY_FAILED';
export const GET_LIST_DISTRICT_NOTARY_SUCCESS = 'GET_LIST_DISTRICT_NOTARY_SUCCESS';
export const GET_LIST_DISTRICT_NOTARY = 'GET_LIST_DISTRICT_NOTARY';

export const REMOVE_LIST = 'REMOVE_LIST'

export const SAVE_STAFF_SELECTED = 'SAVE_STAFF_SELECTED';

export const RESET_STATE_NOTARY_STAFF = 'RESET_STATE_NOTARY_STAFF';
