export const RESET_STATE_EDIT_USER = 'RESET_STATE_EDIT_USER'
export const POST_EDIT_BY_USER = 'POST_EDIT_BY_USER'
export const POST_EDIT_BY_USER_START = 'POST_EDIT_BY_USER_START'
export const POST_EDIT_BY_USER_SUCCESS = 'POST_EDIT_BY_USER_SUCCESS'
export const POST_EDIT_BY_USER_FAILED = 'POST_EDIT_BY_USER_FAILED'

export const GET_LIST_ETHNIC = 'GET_LIST_ETHNIC'
export const GET_LIST_ETHNIC_START = 'GET_LIST_ETHNIC_START'
export const GET_LIST_ETHNIC_SUCCESS = 'GET_LIST_ETHNIC_SUCCESS'
export const GET_LIST_ETHNIC_FAILED = 'GET_LIST_ETHNIC_FAILED'

