export const DEFAULT_ACTION = 'Edit/DEFAULT_ACTION';

export const GET_APPOINTMENT_DETAIL_ACTION = 'Edit/GET_APPOINTMENT_DETAIL_ACTION';
export const GET_APPOINTMENT_DETAIL_COMPLETE = 'Edit/GET_APPOINTMENT_DETAIL_COMPLETE';

export const GET_APPOINTMENT_UPDATE_ACTION = 'Edit/GET_APPOINTMENT_UPDATE_ACTION';
export const GET_APPOINTMENT_UPDATE_COMPLETE = 'Edit/GET_APPOINTMENT_UPDATE_COMPLETE';
