export const GET_LIST_NOTARY_OFFICE_START = 'GET_LIST_NOTARY_OFFICE_START';
export const GET_LIST_NOTARY_OFFICE_FAILED = 'GET_LIST_NOTARY_OFFICE_FAILED';
export const GET_LIST_NOTARY_OFFICE_SUCCESS = 'GET_LIST_NOTARY_OFFICE_SUCCESS';
export const GET_LIST_NOTARY_OFFICE = 'GET_LIST_NOTARY_OFFICE';

export const GET_LIST_NOTARY_OFFICE_BY_SERVICEID_START = 'GET_LIST_NOTARY_OFFICE_BY_SERVICEID_START';
export const GET_LIST_NOTARY_OFFICE_BY_SERVICEID_FAILED = 'GET_LIST_NOTARY_OFFICE_BY_SERVICEID_FAILED';
export const GET_LIST_NOTARY_OFFICE_BY_SERVICEID_SUCCESS = 'GET_LIST_NOTARY_OFFICE_BY_SERVICEID_SUCCESS';
export const GET_LIST_NOTARY_OFFICE_BY_SERVICEID = 'GET_LIST_NOTARY_OFFICE_BY_SERVICEID';

export const LOAD_MORE_LIST_NOTARY_OFFICE_START = 'LOAD_MORE_LIST_NOTARY_OFFICE_START';
export const LOAD_MORE_LIST_NOTARY_OFFICE_FAILED = 'LOAD_MORE_LIST_NOTARY_OFFICE_FAILED';
export const LOAD_MORE_LIST_NOTARY_OFFICE_SUCCESS = 'LOAD_MORE_LIST_NOTARY_OFFICE_SUCCESS';
export const LOAD_MORE_LIST_NOTARY_OFFICE = 'LOAD_MORE_LIST_NOTARY_OFFICE';

export const REFRESH_LIST_NOTARY_OFFICE_START = 'REFRESH_LIST_NOTARY_OFFICE_START';
export const REFRESH_LIST_NOTARY_OFFICE_FAILED = 'REFRESH_LIST_NOTARY_OFFICE_FAILED';
export const REFRESH_LIST_NOTARY_OFFICE_SUCCESS = 'REFRESH_LIST_NOTARY_OFFICE_SUCCESS';
export const REFRESH_LIST_NOTARY_OFFICE = 'REFRESH_LIST_NOTARY_OFFICE';
// Tỉnh thành phố
export const GET_LIST_ADDRESS_CITY_START= 'GET_LIST_ADDRESS_CITY_START';
export const GET_LIST_ADDRESS_CITY_FAILED = 'GET_LIST_ADDRESS_CITY_FAILED';
export const GET_LIST_ADDRESS_CITY_SUCCESS = 'GET_LIST_ADDRESS_CITY_SUCCESS';
export const GET_LIST_ADDRESS_CITY = 'GET_LIST_ADDRESS_CITY';

// Quận Huyện
export const GET_LIST_DISTRICT_START= 'GET_LIST_DISTRICT_START';
export const GET_LIST_DISTRICT_FAILED = 'GET_LIST_DISTRICT_FAILED';
export const GET_LIST_DISTRICT_SUCCESS = 'GET_LIST_DISTRICT_SUCCESS';
export const GET_LIST_DISTRICT = 'GET_LIST_DISTRICT';

// Xã Phường
export const GET_LIST_WARD = 'GET_LIST_WARD';
export const GET_LIST_WARD_START= 'GET_LIST_WARD_START';
export const GET_LIST_WARD_FAILED = 'GET_LIST_WARD_FAILED';
export const GET_LIST_WARD_SUCCESS = 'GET_LIST_WARD_SUCCESS';
// dân tộc
export const GET_LIST_ETHNIC = 'GET_LIST_ETHNIC';
export const GET_LIST_ETHNIC_START= 'GET_LIST_ETHNIC_START';
export const GET_LIST_ETHNIC_FAILED = 'GET_LIST_ETHNIC_FAILED';
export const GET_LIST_ETHNIC_SUCCESS = 'GET_LIST_ETHNIC_SUCCESS';
// Trình độ chuyện môn
export const GET_LIST_QUALIFICATION = 'GET_LIST_QUALIFICATION';
export const GET_LIST_QUALIFICATION_START= 'GET_LIST_QUALIFICATION_START';
export const GET_LIST_QUALIFICATION_FAILED = 'GET_LIST_QUALIFICATION_FAILED';
export const GET_LIST_QUALIFICATION_SUCCESS = 'GET_LIST_QUALIFICATION_SUCCESS';
// Trình độ học vấn
export const GET_LIST_EDUCATION_LEVEL = 'GET_LIST_EDUCATION_LEVEL';
export const GET_LIST_EDUCATION_LEVEL_START= 'GET_LIST_EDUCATION_LEVEL_START';
export const GET_LIST_EDUCATION_LEVEL_FAILED = 'GET_LIST_EDUCATION_LEVEL_FAILED';
export const GET_LIST_EDUCATION_LEVEL_SUCCESS = 'GET_LIST_EDUCATION_LEVEL_SUCCESS';
//Update
export const UPDATE_OFFICE = 'UPDATE_OFFICE';
export const UPDATE_OFFICE_START = 'UPDATE_OFFICE_START';
export const UPDATE_OFFICE_FAILED = 'UPDATE_OFFICE_FAILED';
export const UPDATE_OFFICE_SUCCESS = 'UPDATE_OFFICE_SUCCESS';


export const GET_LIST_NOTARY_SERVICE_BY_OFFICE_ID_START = 'GET_LIST_NOTARY_SERVICE_BY_OFFICE_ID_START';
export const GET_LIST_NOTARY_SERVICE_BY_OFFICE_ID_FAILED = 'GET_LIST_NOTARY_SERVICE_BY_OFFICE_ID_FAILED';
export const GET_LIST_NOTARY_SERVICE_BY_OFFICE_ID_SUCCESS = 'GET_LIST_NOTARY_SERVICE_BY_OFFICE_ID_SUCCESS';
export const GET_LIST_NOTARY_SERVICE_BY_OFFICE_ID = 'GET_LIST_NOTARY_SERVICE_BY_OFFICE_ID';

export const RESET_STATE_NOTARY_OFFICE = 'RESET_STATE_NOTARY_OFFICE';
