export const REGISTER_START = 'REGISTER_START';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER = 'REGISTER';

export const RESET_STATE_REGISTER = 'RESET_STATE_REGISTER';
