
export const GET_DATA_CAPGIAYXNKT_SUCCESS = 'GET_DATA_CAPGIAYXNKT_SUCCESS';
export const GET_DATA_CAPGIAYXNKT = 'GET_DATA_CAPGIAYXNKT';
export const RESET_DATA_CAPGIAYXNKT = 'RESET_DATA_CAPGIAYXNKT';

export const POST_CAPGIAYXNKT_SUCCESS = 'POST_CAPGIAYXNKT_SUCCESS';
export const POST_CAPGIAYXNKT = 'POST_CAPGIAYXNKT';
