export const RESET_STATE_HISTORY_NOTARY = 'RESET_STATE_HISTORY_NOTARY'

export const GET_LIST_HISTORY_NOTARY = 'GET_LIST_HISTORY_NOTARY'
export const GET_LIST_HISTORY_NOTARY_START = 'GET_LIST_HISTORY_NOTARY_START'
export const GET_LIST_HISTORY_NOTARY_SUCCESS = 'GET_LIST_HISTORY_NOTARY_SUCCESS'
export const GET_LIST_HISTORY_NOTARY_FAILED = 'GET_LIST_HISTORY_NOTARY_FAILED'

export const REFRESH_LIST_HISTORY_NOTARY = 'REFRESH_LIST_HISTORY_NOTARY'
export const REFRESH_LIST_HISTORY_NOTARY_START = 'REFRESH_LIST_HISTORY_NOTARY_START'
export const REFRESH_LIST_HISTORY_NOTARY_SUCCESS = 'REFRESH_LIST_HISTORY_NOTARY_SUCCESS'
export const REFRESH_LIST_HISTORY_NOTARY_FAILED = 'REFRESH_LIST_HISTORY_NOTARY_FAILED'

export const LOAD_MORE_LIST_HISTORY_NOTARY = 'LOAD_MORE_LIST_HISTORY_NOTARY'
export const LOAD_MORE_LIST_HISTORY_NOTARY_START = 'LOAD_MORE_LIST_HISTORY_NOTARY_START'
export const LOAD_MORE_LIST_HISTORY_NOTARY_SUCCESS = 'LOAD_MORE_LIST_HISTORY_NOTARY_SUCCESS'
export const LOAD_MORE_LIST_HISTORY_NOTARY_FAILED = 'LOAD_MORE_LIST_HISTORY_NOTARY_FAILED'
