export const UPDATE_AVATAR = 'UPDATE_AVATAR';
export const UPDATE_AVATAR_START = 'UPDATE_AVATAR_START';
export const UPDATE_AVATAR_SUCCESS = 'UPDATE_AVATAR_SUCCESS';
export const UPDATE_AVATAR_FAILED = 'UPDATE_AVATAR_FAILED';
export const RESET_STATE_UPDATE_AVATAR = 'RESET_STATE_UPDATE_AVATAR'; 
