export const GET_LIST_NOTIFICATION_START = 'GET_LIST_NOTIFICATION_START';
export const GET_LIST_NOTIFICATION_FAILED = 'GET_LIST_NOTIFICATION_FAILED';
export const GET_LIST_NOTIFICATION_SUCCESS = 'GET_LIST_NOTIFICATION_SUCCESS';
export const GET_LIST_NOTIFICATION = 'GET_LIST_NOTIFICATION';

export const XAC_DINH_MUC_DO_START = 'XAC_DINH_MUC_DO_START';
export const XAC_DINH_MUC_DO_FAILED = 'XAC_DINH_MUC_DO_FAILED';
export const XAC_DINH_MUC_DO_SUCCESS = 'XAC_DINH_MUC_DO_SUCCESS';
export const XAC_DINH_MUC_DO= 'XAC_DINH_MUC_DO';

export const LOAD_MORE_LIST_NOTIFICATION_START = 'LOAD_MORE_LIST_NOTIFICATION_START';
export const LOAD_MORE_LIST_NOTIFICATION_FAILED = 'LOAD_MORE_LIST_NOTIFICATION_FAILED';
export const LOAD_MORE_LIST_NOTIFICATION_SUCCESS = 'LOAD_MORE_LIST_NOTIFICATION_SUCCESS';
export const LOAD_MORE_LIST_NOTIFICATION = 'LOAD_MORE_LIST_NOTIFICATION';


export const CLICK_NOTIFICATION_START = 'CLICK_NOTIFICATION_START';
export const CLICK_NOTIFICATION_FAILED = 'CLICK_NOTIFICATION_FAILED';
export const CLICK_NOTIFICATION_SUCCESS = 'CLICK_NOTIFICATION_SUCCESS';
export const CLICK_NOTIFICATION = 'CLICK_NOTIFICATION';

export const GET_LIST_NEW_NOTIFICATION_START = 'GET_LIST_NEW_NOTIFICATION_START';
export const GET_LIST_NEW_NOTIFICATION_FAILED = 'GET_LIST_NEW_NOTIFICATION_FAILED';
export const GET_LIST_NEW_NOTIFICATION_SUCCESS = 'GET_LIST_NEW_NOTIFICATION_SUCCESS';
export const GET_LIST_NEW_NOTIFICATION = 'GET_LIST_NEW_NOTIFICATION';

export const GET_DETAIL_NOTIFICATION_START = 'GET_DETAIL_NOTIFICATION_START';
export const GET_DETAIL_NOTIFICATION_FAILED = 'GET_DETAIL_NOTIFICATION_FAILED';
export const GET_DETAIL_NOTIFICATION_SUCCESS = 'GET_DETAIL_NOTIFICATION_SUCCESS';
export const GET_DETAIL_NOTIFICATION = 'GET_DETAIL_NOTIFICATION';

export const RESET_STATE_NOTIFICATION = 'RESET_STATE_NOTIFICATION';
