export const DEFAULT_ACTION = 'disabilityAccept/DEFAULT_ACTION';

export const CAP_NHAT_NOI_DUNG_ACTION = 'CAP_NHAT_NOI_DUNG_ACTION';
export const CAP_NHAT_NOI_DUNG_COMPLETE = 'CAP_NHAT_NOI_DUNG_COMPLETE';

export const XAC_NHAN_KT_ACTION = 'XAC_NHAN_KT_ACTION';
export const XAC_NHAN_KT_COMPLETE = 'XAC_NHAN_KT_COMPLETE';
