export const icons = {
  back: require('./source/arrow-left.png'),
  bullet: require('./source/bullet.png'),
  facebook: require('./source/fb.png'),
  apple: require('./source/apple.png'),
  google: require('./source/google.png'),
  add_user: require('./source/add_user.png'),
  close: require('./source/close.png'),
  eye: require('./source/view_eye.png'),
  eye_dis: require('./source/view_eye_dis.png'),
  ic_web_white: require('./source/ic_web_white.png'),
  ic_sms: require('./source/ic_sms.png'),
  user: require('./source/user.png'),
  move_left: require('./source/move_left.png'),
  tab_home: require('./source/tab_home.png'),
  tab_chat: require('./source/tab_chat.png'),
  tab_notify: require('./source/tab_notify.png'),
  tab_profileCC: require('./source/tab_profile_cc.png'),
  tab_user: require('./source/tab_user.png'),
  create_profile_cc: require('./source/create_profile_cc.png'),
  icon_web: require('./source/ic_location.png'),
  icon_folder: require('./source/ic_folder.png'),
  icon_back_gray: require('./source/ic_back.png'),
  clock: require('./source/clock.png'),
  user_cc: require('./source/user_cc.png'),
  location: require('./source/location.png'),
  search: require('./source/search.png'),
  more_horizontal: require('./source/more_h.png'),
  user_add: require('./source/user_add.png'),
  filter: require('./source/filter.png'),
  mail: require('./source/mail.png'),
  chevron_right: require('./source/chevron_right.png'),
  file_complete: require('./source/file_complete.png'),
  warn: require('./source/warn.png'),
  user_1: require('./source/user_1.png'),
  folder: require('./source/folder.png'),
  setting: require('./source/setting.png'),
  phone: require('./source/phone.png'),
  time: require('./source/time.png'),
  info: require('./source/info.png'),
  info_red: require('./source/info_red.png'),
  power: require('./source/power.png'),
  mes: require('./source/mes.png'),
  star: require('./source/star.png'),
  show_list: require('./source/show_list.png'),
  drop_down: require('./source/drop_down.png'),
  location_2: require('./source/location_2.png'),
  start_full: require('./source/star_full.png'),
  drop_line: require('./source/drop_line.png'),
  user_in: require('./source/ic_user_in.png'),
  user_tick: require('./source/ic_user_tick.png'),
  camera: require('./source/ic_camera.png'),
  picture: require('./source/ic_picture.png'),
  tick_success: require('./source/tick_success.png'),
  warn_red: require('./source/warn_red.png'),
  checked: require('./source/ic_checked.png'),
  non_checked: require('./source/ic_non_checked.png'),
  logo_confirm: require('./source/logo_confirm.png'),
  card: require('./source/ic_card.png'),
  copy: require('./source/ic_copy.png'),
  checked_line: require('./source/ic_checked_line.png'),
  non_checked_line: require('./source/checkBoxOff.png'),
  tick_round: require('./source/ic_tick_round.png'),
  vnpay: require('./source/logo_vnpay.png'),
  vtcpay: require('./source/vtcpay.png'),
  visa: require('./source/logo_visa.png'),
  union: require('./source/logo_union.png'),
  tick_done:require('./source/ic_done.png'),
  ic_flash_off:require('./source/ic_flash_off.png'),
  ic_flash_on:require('./source/ic_flash_on.png'),
  ic_flash_auto:require('./source/ic_flash_auto.png'),
  ic_rotate_cam:require('./source/ic_rotate_cam.png'),
  star_rating: require('./source/star_rating.png'),
  star_rating_full: require('./source/star_rating_full.png'),
  complete: require('./source/complete.png'),
  left_gray: require('./source/left-gray.png'),
  mes_red: require('./source/mes_red.png'),
  more: require('./source/more.png'),
  online: require('./source/Status_online.png'),
  offline: require('./source/Status_offline.png'),
  timer: require('./source/timer.png'),
  pictureIcon: require('./source/picture.png'),
  staple: require('./source/staple.png'),
  send: require('./source/ic_send.png'),
  document: require('./source/document.png'),
  search_gray: require('./source/search_gray.png'),
  arrow_right: require('./source/arrow_right.png'),
  arrow_around: require('./source/arrow_around.png'),
  money: require('./source/money.png'),
  privacy: require('./source/privacy.png'),
  terms: require('./source/terms.png'),
  dvcc:require('./source/ic_dvcc.png'),
  ic_delete:require('./source/ic_delete.png'),
  capture: require('./source/ic_capture.png'),
  payoo_logo: require('./source/payoo-logo.png'),
  marker: require('./source/marker.png'),
  // menu: require('./source/menu.png'),
};

export type IconTypes = keyof typeof icons;
