export const RESET_STATE_CREATE = 'RESET_STATE_CREATE';

// Lấy dịch vụ loại 2
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_START = 'CHANGE_PASSWORD_START';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';


export const RESET_STATE_CHANGE_PASSWORD = "RESET_STATE_CHANGE_PASSWORD";

