export const GET_TERM_START = 'GET_TERM_START';
export const GET_TERM_FAILED = 'GET_TERM_FAILED';
export const GET_TERM_SUCCESS = 'GET_TERM_SUCCESS';
export const GET_TERM = 'GET_TERM';

export const GET_PRIVACY_START = 'GET_PRIVACY_START';
export const GET_PRIVACY_FAILED = 'GET_PRIVACY_FAILED';
export const GET_PRIVACY_SUCCESS = 'GET_PRIVACY_SUCCESS';
export const GET_PRIVACY = 'GET_PRIVACY';

export const RESET_STATE_TERM = 'RESET_STATE_TERM';
