// Get list room chat
export const GET_LIST_ROOM_CHAT_START = 'GET_LIST_ROOM_CHAT_START';
export const GET_LIST_ROOM_CHAT_FAILED = 'GET_LIST_ROOM_CHAT_FAILED';
export const GET_LIST_ROOM_CHAT_SUCCESS = 'GET_LIST_ROOM_CHAT_SUCCESS';
export const GET_LIST_ROOM_CHAT = 'GET_LIST_ROOM_CHAT';

export const REFRESH_LIST_ROOM_CHAT_START = 'REFRESH_LIST_ROOM_CHAT_START';
export const REFRESH_LIST_ROOM_CHAT_FAILED = 'REFRESH_LIST_ROOM_CHAT_FAILED';
export const REFRESH_LIST_ROOM_CHAT_SUCCESS = 'REFRESH_LIST_ROOM_CHAT_SUCCESS';
export const REFRESH_LIST_ROOM_CHAT = 'REFRESH_LIST_ROOM_CHAT';

// Create room chat
export const CREATE_ROOM_START = 'CREATE_ROOM_START';
export const CREATE_ROOM_FAILED = 'CREATE_ROOM_FAILED';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_ROOM = 'CREATE_ROOM';

// Get info room chat
export const GET_INFO_ROOM_START = 'GET_INFO_ROOM_START';
export const GET_INFO_ROOM_FAILED = 'GET_INFO_ROOM_FAILED';
export const GET_INFO_ROOM_SUCCESS = 'GET_INFO_ROOM_SUCCESS';
export const GET_INFO_ROOM = 'GET_INFO_ROOM';

// Join room chat
export const JOIN_ROOM = 'JOIN_ROOM';
export const JOIN_ROOM_FAILED = 'JOIN_ROOM_FAILED';
export const JOIN_ROOM_SUCCESS = 'JOIN_ROOM_SUCCESS';
export const JOIN_ROOM_START = 'JOIN_ROOM_START';

// Get list message in room
export const GET_MESSAGE_START = 'GET_MESSAGE_START';
export const GET_MESSAGE_FAILED = 'GET_MESSAGE_FAILED';
export const GET_MESSAGE_SUCCESS = 'GET_MESSAGE_SUCCESS';
export const GET_MESSAGE = 'GET_MESSAGE';

// Send message
export const SEND_MESSAGE_START = 'SEND_MESSAGE_START';
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE = 'SEND_MESSAGE';

// Add message to data
export const ADD_MESSAGE = 'ADD_MESSAGE';

// Save room working
export const SAVE_ROOM_WORKING = 'SAVE_ROOM_WORKING';

// Reset state
export const RESET_ROOM_WORKING = 'RESET_ROOM_WORKING';
export const RESET_STATE_LIST_ROOM_CHAT = 'RESET_STATE_LIST_ROOM_CHAT';
export const RESET_STATE_ALL = 'RESET_STATE_ALL';


// Get info room chat
export const UPDATE_READ_MESSAGE_START = 'UPDATE_READ_MESSAGE_START';
export const UPDATE_READ_MESSAGE_FAILED = 'UPDATE_READ_MESSAGE_FAILED';
export const UPDATE_READ_MESSAGE_SUCCESS = 'UPDATE_READ_MESSAGE_SUCCESS';
export const UPDATE_READ_MESSAGE = 'UPDATE_READ_MESSAGE';
