
export const GET_LIST_PERSONAL_PAPER = 'GET_LIST_PERSONAL_PAPER'
export const GET_LIST_PERSONAL_PAPER_START = 'GET_LIST_PERSONAL_PAPER_START'
export const GET_LIST_PERSONAL_PAPER_SUCCESS = 'GET_LIST_PERSONAL_PAPER_SUCCESS'
export const GET_LIST_PERSONAL_PAPER_FAILED = 'GET_LIST_PERSONAL_PAPER_FAILED'

export const DELETE_PERSONAL_PAPER = 'DELETE_PERSONAL_PAPER'
export const DELETE_PERSONAL_PAPER_START = 'DELETE_PERSONAL_PAPER_START'
export const DELETE_PERSONAL_PAPER_SUCCESS = 'DELETE_PERSONAL_PAPER_SUCCESS'
export const DELETE_PERSONAL_PAPER_FAILED = 'DELETE_PERSONAL_PAPER_FAILED'

export const RESET_STATE_PERSONAL_PAPERS = 'RESET_STATE_PERSONAL_PAPERS'