export const DEFAULT_ACTION = 'DETAIL_DISABILITY/DEFAULT_ACTION';

export const GET_DETAIL_DISABILITY_ACTION = 'GET_DETAIL_DISABILITY_ACTION';
export const GET_DETAIL_DISABILITY_COMPLETE = 'GET_DETAIL_DISABILITY_COMPLETE';

export const DUYET_TIEP_NHAN_ACTION = 'DUYET_TIEP_NHAN_ACTION';
export const DUYET_TIEP_NHAN_COMPLETE = 'DUYET_TIEP_NHAN_COMPLETE';

export const KHONG_DUYET_TIEP_NHAN_ACTION = 'KHONG_DUYET_TIEP_NHAN_ACTION';
export const KHONG_DUYET_TIEP_NHAN_COMPLETE = 'KHONG_DUYET_TIEP_NHAN_COMPLETE';
